from lab3 import app, Category, Task, db, Group, Teacher, Student

with app.app_context():
    category1 = Category(name='cat1')
    category2 = Category(name='cat2')
    task1 = Task(status=0, name='task1', description='task1 description', difficult=5, id_category=1)
    task2 = Task(status=0, name='task2', description='task2 description', difficult=5, id_category=1)
    group1 = Group(number=123)
    group2 = Group(number=124)
    teacher1 = Teacher(name='Alex')
    teacher2 = Teacher(name='Ivan')
    student1 = Student(name='Oleg')
    student2 = Student(name='Nikita')
    db.session.add(category1)
    db.session.add(category2)
    db.session.add(task1)
    db.session.add(task2)
    db.session.add(group1)
    db.session.add(group2)
    db.session.add(teacher1)
    db.session.add(teacher2)
    db.session.add(student1)
    db.session.add(student2)
    db.session.commit()
